// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Mgm2lAB9wqM9c8rL4ybrVkO1j_vFx_8',
    appId: '1:510877610885:web:7888294346dd4f195d0aec',
    messagingSenderId: '510877610885',
    projectId: 'ar-moustaches-app',
    authDomain: 'ar-moustaches-app.firebaseapp.com',
    storageBucket: 'ar-moustaches-app.appspot.com',
    measurementId: 'G-FK7XLB7T6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6d_NU0Y3wAiqz-fIP4wXJnWS32oZ0-dI',
    appId: '1:510877610885:android:53f88f3e06e20b225d0aec',
    messagingSenderId: '510877610885',
    projectId: 'ar-moustaches-app',
    storageBucket: 'ar-moustaches-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS9Ugbb7DwymyV7FGRWTMG7zPjp0M6758',
    appId: '1:510877610885:ios:b0e12328cdf531f15d0aec',
    messagingSenderId: '510877610885',
    projectId: 'ar-moustaches-app',
    storageBucket: 'ar-moustaches-app.appspot.com',
    iosBundleId: 'com.example.moustacheAr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS9Ugbb7DwymyV7FGRWTMG7zPjp0M6758',
    appId: '1:510877610885:ios:9bf98aa8001dcb435d0aec',
    messagingSenderId: '510877610885',
    projectId: 'ar-moustaches-app',
    storageBucket: 'ar-moustaches-app.appspot.com',
    iosBundleId: 'com.example.moustacheAr.RunnerTests',
  );
}
